### ISSUE TITLE
Alignment at categories

### ISSUE THREAD

**Issue by ghost** [mor10/popper#17] opened 2018-03-05 14:08 UTC
Hi,

If we are surfing with Popper to example.com/category/category-item. Than at the first picture you'll see that the text will not be aligned at a Motorola X Play smartphone and Google Chrome.

Here an example: https://edwarddekker.nl/category/ict

Regards,
Edward

**Comment by Zodiac1978** [comment] 2021-01-16 14:53
Not able to reproduce this error and no screenshots provided. Closing.

**Closed as completed by Zodiac1978** 2021-01-16 14:53 UTC
